services:
  - type: web
    name: checklistinator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run checklistinator.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.13"
